name: euro
description: A new Flutter project.

publish_to: "none"

version: 5.1.0+50010

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any

  responsive_framework: ^1.5.1

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  dio: ^5.7.0

  hive_flutter: ^1.1.0

  shared_preferences: ^2.3.2

  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0

  image_picker: ^1.1.2

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpeg/
    - assets/text/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic/NotoNaskhArabic.ttf
